### ISSUE TITLE
Solidity-compatible checkpoint digest in MultisigIsm

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/fuel-contracts#21]
* Address the TODO here https://github.com/hyperlane-xyz/fuel-contracts/pull/16/files#diff-2d4bf727d8c6d033af18d47bbe346f2362df252e12a7f17987a476fa49a0959cR15
* We need to make sure that the checkpoint digest that is signed by validators is constructed in Sway in the exact same way as it's done in Solidity. Otherwise we can't leverage the existing signatures by validators
* See https://github.com/hyperlane-xyz/fuel-contracts/pull/16#discussion_r1042308644 for context

**Comment by nambrot** [comment]
Is this still open/in review?

**Comment by yorhodes** [comment]
> Is this still open/in review?

yes
