### ISSUE TITLE
Move away from Vec<u8> to the Bytes type

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/fuel-contracts#22]
https://github.com/FuelLabs/sway/pull/3454 was finally merged, adding the `Bytes` type.

This doesn't help too much with encoding / decoding of structs into the Bytes type, so this probably isn't the best candidate for `EncodedMessage` (at least for now). It also doesn't have keccak or log support like `EncodedMessage`.

However we should move to the Bytes type for the message body instead of a Vec<u8>

Maybe blocked on the lack of a Sway release since the merging of Bytes?

**Comment by tkporter** [comment]
Blocked by https://github.com/FuelLabs/fuels-rs/issues/723

**Comment by tkporter** [comment]
Sorta blocked by https://github.com/FuelLabs/fuels-rs/pull/904 for using Bytes as an input

**Comment by tkporter** [comment]
Fuels-ts also doesn't have Bytes support yet.. I feel like we should consider having a Vec<u8> version and Bytes version of important functions, like:
```
    #[storage(read, write)]
    fn dispatch_vec_u8(destination_domain: u32, recipient: b256, message_body: Vec<u8>) -> b256;

    #[storage(read, write)]
    fn dispatch(
        destination_domain: u32,
        recipient: b256,
        message_body: Bytes,
    ) -> b256;
```

**Comment by yorhodes** [comment]
also noticed https://github.com/FuelLabs/sway/issues/4419
