### ISSUE TITLE
MultisigIsm: implement it!

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/fuel-contracts#7]
Imlement the MultisigIsm as a separate Sway package / contract

Useful: https://fuellabs.github.io/sway/v0.31.1/blockchain-development/hashing_and_cryptography.html?highlight=signature#signature-recovery
https://github.com/FuelLabs/sway/blob/master/sway-lib-std/src/vm/evm/ecr.sw#L12

**Comment by yorhodes** [comment]
> Is this still open/in review?

yes
